### PR TITLE
Initial page contents

### PR DESCRIPTION
**Pull request by BalduinLandolt**
To do:

- [x] Add `Home` page contents
- [x] Add `About` page scaffolding
- [ ] Finalize `About` page
- [x] Write short post on the workshop/network foundation
- [x] Write short post on the pages/website launch
- [x] write page about the mailing list

### CODE REVIEW

**Comment by BalduinLandolt** [comment]
the "about" page is now getting rather long (and will continue so), so I'm wondering if we should split "people" out into a separate page?

**Comment by BalduinLandolt** [comment]
I think this is good enough for now. The missing descriptions, and possibly more/better content can be added in a separate PR. I think it would be nice to get this merged and online as soon as possible.

**Comment by kraus-s** [comment]
Aye.

Balduin Landolt ***@***.***> schrieb am Sa., 3. Dez. 2022,
11:51:

**Review by kraus-s — APPROVED** [review]
Thank you!

**Review by ElineElmiger — APPROVED** [review]
changed a few things in the text

**Pull request merged**
